# Generated by Django 6.0.6 on 2026-07-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('FOUND', 'Found'), ('SCHEDULED', 'Viewing Scheduled'), ('APPLIED', 'Applied'), ('SIGNED', 'Lease Signed')], default='FOUND', max_length=15)),
                ('campus_distance', models.FloatField(help_text='Distance in miles')),
                ('transit_proximity', models.IntegerField(help_text='Scale 1-5')),
                ('wifi_capability', models.IntegerField(help_text='Scale 1-5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
